---
- name: Update XML file
  hosts: localhost
  gather_facts: no

  vars:
    xml_file_path: "/Users/bajoris/git/update_xml/files/ssh.xml"
    hostname: "dev.customer.com"
    username: admin

  tasks:
    - name: Update user in XML file using lineinfile
      lineinfile:
        path: "{{ xml_file_path }}"
        regexp: '<user>username</user>'
        line: '<user>{{ username }}</user>'
        backrefs: yes
        backup: yes
      
    - name: Ensure a new element exists
      lineinfile:
        path: "{{ xml_file_path }}"
        insertafter: '</global-settings>'
        line: '  <new_element>some_value</new_element>'

    - name: Add new host block with blockinfile
      blockinfile:
        path: "{{ xml_file_path }}"
        insertbefore: "</ssh-config>"
        block: |
          <host>
            <name>example-server2</name>
            <hostname>new.example.com</hostname>
            <port>2222</port>
            <user>newuser</user>
            <identity-file>~/.ssh/new_server_rsa</identity-file>
            <forward-agent>yes</forward-agent>
          </host>

    - name: Ensure a new element exists
      xml:
        path: "{{ xml_file_path }}"
        xpath: "/ssh-config/global-settings"
        add_children:
          - new_element: "some_value"
